# Generated by Django 4.2.9 on 2024-02-15 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_author_keyword_panelist_alter_post_slug_thesis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='panelists',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.DeleteModel(
            name='Panelist',
        ),
        migrations.DeleteModel(
            name='Thesis',
        ),
    ]
